### ISSUE TITLE
the pandoc-ruby with sinatra is not work

### ISSUE THREAD

**Issue by kimurayuuki** [xwmx/pandoc-ruby#22]
the pandoc-ruby with sinatra is not work in my environment.
How can this problem be solved or circumvented?

### sinatra's error
```
[root@kimura test_app]# ruby app.rb
[2016-11-08 14:11:06] INFO  WEBrick 1.3.1
[2016-11-08 14:11:06] INFO  ruby 2.3.0 (2015-12-25) [x86_64-linux]
== Sinatra (v1.4.7) has taken the stage on 4567 for production with backup from WEBrick
[2016-11-08 14:11:06] INFO  WEBrick::HTTPServer#start: pid=25402 port=4567
2016-11-08 14:11:10 - Errno::ENOENT - No such file or directory - pandoc:
        /root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open3.rb:199:in `spawn'
        /root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
        /root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open3.rb:95:in `popen3'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pandoc-ruby-2.0.1/lib/pandoc-ruby.rb:206:in `execute'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pandoc-ruby-2.0.1/lib/pandoc-ruby.rb:198:in `execute_pandoc'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pandoc-ruby-2.0.1/lib/pandoc-ruby.rb:190:in `convert_string'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pandoc-ruby-2.0.1/lib/pandoc-ruby.rb:132:in `convert'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pandoc-ruby-2.0.1/lib/pandoc-ruby.rb:166:in `block (2 levels) in <class:PandocRuby>'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt/pandoc.rb:42:in `evaluate'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt/template.rb:102:in `render'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:823:in `render'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:710:in `markdown'
        app.rb:25:in `block in <main>'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
        /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
        /root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        /root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        /root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
172.16.50.20 - - [08/Nov/2016:14:11:10 +0900] "GET /markdown_template_page HTTP/1.1" 500 30 0.0103
172.16.50.20 - - [08/Nov/2016:14:11:10 JST] "GET /markdown_template_page HTTP/1.1" 500 30
- -> /markdown_template_page
```

### app versions
pandoc 1.17.2
pandoc-ruby (2.0.1)
ruby 2.3.0p0
sinatra (1.4.7)
gem 2.5.1

### gem lists

backports (3.6.8)
bigdecimal (1.2.8, 1.2.7)
bundle (0.0.1)
bundler (1.13.6)
did_you_mean (1.0.2, 1.0.0)
io-console (0.4.6, 0.4.5)
json (2.0.2, 1.8.3)
mail (2.6.4)
mime-types (3.1)
mime-types-data (3.2016.0521)
minitest (5.9.1, 5.8.3)
multi_json (1.12.1)
net-telnet (0.1.1)
pandoc-ruby (2.0.1, 1.0.0)
power_assert (0.3.1, 0.2.6)
psych (2.1.1, 2.0.17)
rack (2.0.1, 1.6.4)
rack-protection (1.5.3)
rack-test (0.6.3)
rake (11.3.0, 10.4.2)
rdoc (5.0.0, 4.2.1)
redcarpet (3.3.4)
rubygems-update (2.6.8)
sinatra (1.4.7)
sinatra-contrib (1.4.7)
sinatra-reloader (1.0)
test-unit (3.2.2, 3.1.5)
tilt (2.0.5)

**Comment by xwmx** [comment]
In the trace above it looks like Ruby can't find the `pandoc` executable. To make `pandoc` available, make sure it's set in the `$PATH` environment variable. Alternatively, you can tell PandocRuby where to find the executable by setting `PandocRuby.pandoc_path`:

```ruby
PandocRuby.pandoc_path = '/path/to/pandoc'
```
